### PR TITLE
fix: Resume connection before continuing. [#77]

### LINKED ISSUE #77: Socket stops accepting messages
I'm kind of loosing my mind over this...

## 🐛 Bug Report

Server-side socket stops accepting messages, even though the connection remains open and it is still able to send messages.

## To Reproduce

See https://github.com/cope/wtfws for an extremely detail description and ability to clone and repro the issue.

## Expected behavior

Server-side socket to KEEP accepting messages.

## Your Environment

- *node version*: 12.18.3
- *fastify version*: >=3.4.1
- *os*: Windows
- *any other relevant information*: see https://github.com/cope/wtfws

### PR DESCRIPTION
**Pull request by ShogunPanda**
This fixes #77 by resuming the connection before calling the handler.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by ShogunPanda** [comment]
Sure. Will do soon!

File: index.js [hunk 1]
```diff
@@ -12,7 +12,11 @@ function fastifyWebsocket (fastify, opts, next) {
...
   const handle = opts.handle
-    ? (req, res) => opts.handle.call(fastify, req[kWs], req)
+    ? (req, res) => {
+      req[kWs].resume()
+
+      return opts.handle.call(fastify, req[kWs], req)
+    }
     : (req, res) => {
       req[kWs].socket.close()
     }
```
Comment (jsumners) [inline index.js:22]: I think this would be far easier to read if the functions were named and assigned like:

```js
const handle = opts.handle ? wrappedHandler : rawHandler
```

Comment (ShogunPanda) [reply index.js]: Good point. Applied.

File: index.js [hunk 2]
```diff
@@ -78,6 +79,16 @@ function fastifyWebsocket (fastify, opts, next) {
     oldClose.call(this, cb)
   }
 
+  function wsHandle (handle, req, res) {
+    req[kWs].resume()
```
Comment (mcollina) [inline index.js:83]: instead of doing this, can you use the `'addListener'` event and resume _only_ if a new `'message'` event handler is added to the websocket?

**Review by mcollina — CHANGES_REQUESTED** [review]

File: index.js (hunk 2 above)
Comment (ShogunPanda) [reply index.js]: Done :)

**Comment by ShogunPanda** [comment]
Superseded by https://github.com/luin/ioredis/pull/1201 - Closing.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM
